### ISSUE TITLE
Reccommendation

### ISSUE THREAD

**Issue by PixlPlcr** [rube200/PlayerReport#1]
Can you make it so it doesn't Use Mysql. I really dont like having to look through the HeidiSQL Stuff.
It would help if you could do a reports.log or Reports .txt. Something i can do `Type Reports.log` In cmd or batch to send me an email when a new report shows up...

Also. if possible make the log format simple...
for example

[reporter Steamid64] [reporter steam name] : [reported Steamid64] [reported steam name] : [reason]

**Comment by rube200** [comment]
If you do not want to use mysql, just set it up, and it will work fine.
Yes I can do something of the genre like report.log, but it will not serve much for what I intend to do briefly.
